---
title: "ExponentialSmoothing"
author: "Vidhath Raghavan"
date: "2023-03-02"
output: html_document
---

```{r}
df = read.csv('C:/Users/vidha/Time Series/hungary_chickenpox/hungary_chickenpox.csv')

rs = data.frame(df[, -cbind(1)])
df2 = data.frame(df[, 1])
df2$Cases = rowSums(rs)
colnames(df2)[1] = 'Date'
```

## Converting to Monthly
(because ETS() cannot take in frequency > 24)
```{r}
df3 = df2
df3$Date = as.Date(df3$Date, '%d/%m/%Y')
df3 = data.frame(tapply(df3[[2]], format(df3[[1]], '%Y-%m'), sum))
colnames(df3)[1] = 'MonthlyCases'
```

## Creating a Time Series + Train/Test Split
```{r}
ts = ts(df3$MonthlyCases, start = c(2005), frequency = 12)
autoplot(ts)

ts_train = window(ts, end = c(2012,12))
ts_test = window(ts, start = c(2013))

autoplot(ts_train)
```

## Exponential Smoothing
```{r}
ets = ets(ts_train)
summary(ets)
```

## Forecasting
```{r}
fcst = forecast(ets, h = 24)
plot(fcst, xlab = 'Time', ylab = 'Chickenpox Cases in Hungary')
lines(ts_test, col = 2)
legend('top', legend = c('ETS Forecast', 'Actual'), col = c(2, 4), lty = 1)
```

## Error
```{r}
mae = abs(fcst[['mean']] - ts_test)
rmse = sqrt(mean((fcst[['mean']] - ts_test)^2))
aicc = ets$aicc
mae
rmse
aicc
accuracy(fcst, ts_test)
```

## Forecasting till 2020
```{r}
ets2 = ets(ts)

fcst2 = forecast(ets2, h = 60)
plot(fcst2, xlab = 'Time', ylab = 'Chickenpox Cases in Hungary')
```